import * as vscode from 'vscode';

export class ResourcePackGenerator {
    static async generateStructure() {
        const packFormat = await vscode.window.showQuickPick(
            ['12', '13', '14', '15'],
            { placeHolder: 'Select resource pack format (Minecraft version)' }
        );

        return `{
    "pack": {
        "pack_format": ${packFormat},
        "description": "Generated by Nexo VSCode Extension"
    }
}`;
    }
}
